import os
import json
import boto3
from dotenv import load_dotenv
import scrapy 
from math import ceil
from urllib.parse import urljoin
import uuid

software_list = [
    "Account Planning Tools",
    "Accounting Practice Management Software",
    "Accounts Payable Software",
    "Accounts Receivable Software",
    "Auto Dealer Accounting Software",
    "Bookkeeping Services",
    "Budgeting Software",
    "Call Accounting Software",
    "Cash Collection Software",
    "Cash Flow Management Software",
    "Church Accounting Software",
    "Cloud Cost Management Software",
    "Crypto Accounting Software",
    "Fixed Asset Accounting Software",
    "Fund Accounting Software",
    "Lease Accounting Software",
    "Nonprofit Accounting Software",
    "Online Accounting Software",
    "Payroll Accounting Software",
    "QuickBooks Partner",
    "Retail Accounting Software",
    "Tally Partner",
    "Tally Mobile Software",
    "Trust Accounting Software",
    "Arborist Software",
    "Cannabis Software",
    "Dairy Management Software",
    "Farm Management Software",
    "Garden Center Software",
    "Mining Software",
    "Winery Software",
    "App Builder Software",
    "App Design Software",
    "Application Integration Tools",
    "Application Lifecycle Management Software",
    "Application Performance Monitoring Tools",
    "Application Server Software",
    "Application Shielding Software",
    "Automation Testing Tools",
    "Debugging Software",
    "Enterprise Service Bus Software",
    "IoT Software",
    "IoT Device Management Software",
    "Ipaas Software",
    "Low Code Development Platform",
    "Mobile Device Management Software",
    "PaaS Tools",
    "Software Testing Tools",
    "Source Code Management Software",
    "Uber Clone Scripts",
    "Version Control System",
    "AI Design Tools",
    "AI Development Platform",
    "AI Productivity Tools",
    "AI Sales Assistant Software",
    "AI Writing Tools",
    "AR Visualization Software",
    "Augmented Reality Software",
    "Closed Captioning Services",
    "Conversational AI Platform",
    "Generative AI Software",
    "Machine Learning Software",
    "MLOps Platform",
    "Neural Network Software",
    "Smart Home System",
    "Speech Recognition Software",
    "Speech To Text Software",
    "Text To Speech Software",
    "Video Translation Services",
    "Virtual Machine Software",
    "Visual Search Software",
    "Voice Recognition Software",
    "VR Software",
    "Asset Tracking Software",
    "Calibration Software",
    "Digital Asset Management Software",
    "EAM Software",
    "Equipment Leasing Software",
    "Equipment Rental Software",
    "Android Data Recovery Software",
    "Archiving Software",
    "Database Backup Software",
    "Disaster Recovery Software",
    "Disk Cleanup Software",
    "Email Archiving Software",
    "Email Backup Software",
    "Mobile Data Recovery Software",
    "Photo Recovery Software",
    "Saas Backup Software",
    "Video Recovery Software",
    "Barcode Billing Software",
    "Billing And Provisioning Software",
    "E Invoicing Software",
    "EWay Bill Software",
    "GST Software",
    "GST Billing Software",
    "GST Rate Finder Software",
    "GST Reconciliation Software",
    "Legal Billing Software",
    "Medical Billing Software",
    "POS Billing Software",
    "QR Code Generator Software",
    "Recurring Billing Software",
    "Restaurant Billing Software",
    "SaaS Billing Software",
    "Subscription",
    "Supermarket Billing Software",
    "Utility Billing Software",
    "Wholesale Billing Software",
    "Application Virtualization Software",
    "Business Continuity Management Software",
    "Charting Software",
    "Competitive Intelligence Tools",
    "Computer Assisted Translation Software",
    "Conversation Intelligence Software",
    "Corporate Wellness Software",
    "Decision Support Software",
    "Disk Imaging Software",
    "Embedded Analytics Software",
    "IBM Partner",
    "Image Recognition Software",
    "Machine Translation Software",
    "Market Intelligence Software",
    "Mind Mapping Software",
    "Product Analytics Software",
    "Qualitative Data Analysis Software",
    "Transcription Software",
    "Video Analytics Software",
    "Virtual Tour Software",
    "Appointment Management System",
    "Appointment Reminder Software",
    "Association Management Software",
    "Astrology Software",
    "Business Card Scanning Software",
    "Business Plan Software",
    "Business Process Management Software",
    "Business Rules Management System",
    "Business Valuation Software",
    "Change Management Tools",
    "CMMS Software",
    "Company Secretarial Software",
    "Compliance Management Software",
    "Consultancy Software",
    "Contract Analysis Software",
    "Contract Management Software",
    "Corporate Gifting Solutions",
    "Corrective And Preventive Action Software",
    "CPG Software",
    "Drone Services",
    "DSAR Software",
    "Enterprise Mobility Software",
    "Enterprise Performance Management (EPM) Software",
    "Enterprise Search Software",
    "Entity Management Software",
    "Field Service Management Software",
    "Florist Software",
    "Franchise Management Software",
    "Freelance Platform",
    "GDPR Compliance Software",
    "Gig Economy Platform",
    "Handyman Software",
    "Key Management Software",
    "Log Book Software",
    "Log Management Software",
    "Maid Service Software",
    "Mobile Recharge Software",
    "Permit To Work Software",
    "Pest Control Software",
    "Professional Service Automation Software",
    "Regulatory Reporting Software",
    "Safety Management Software",
    "Service Level Agreement Software",
    "Tradesman Job Management Software",
    "Waitlist Software",
    "Waste Management Software",
    "Work Order Software",
    "Auto Dialer Software",
    "Automatic Call Distribution",
    "Business Phone System",
    "Business Phone Number Services",
    "Call Blocking Apps Software",
    "Call Center Knowledge Base Software",
    "Call Forwarding Software",
    "Call Management System",
    "Call Masking Solutions",
    "Call Monitoring Software",
    "Call Recording Software",
    "Call Routing Software",
    "Call Screening Software",
    "Call Tracking Software",
    "Call Transfer Software",
    "Cloud Contact Center Solutions",
    "Cloud IVR Solutions",
    "Cloud PBX System",
    "Cloud Phone System",
    "Cloud Telephony Software",
    "Contact Management Software",
    "Enterprise Phone System",
    "Hosted IVR Solutions",
    "Hosted PBX System",
    "Hosted Phone System",
    "Inbound Call Center Software",
    "Intelligent Phone System",
    "IVR Software",
    "Omnichannel Contact Center Software",
    "Outbound Call Center Software",
    "Predictive Dialer Software",
    "Softphone Software",
    "Speech Analytics Software",
    "Telecommunication Software",
    "Virtual Business Phone Services",
    "Virtual Call Center Software",
    "Virtual PBX System",
    "Virtual Phone System",
    "VOIP Software",
    "VoIP Phone Services",
    "Application Sharing Software",
    "Audio Conferencing Software",
    "Board Management Software",
    "Board Meeting Software",
    "Cloud Communication Platform",
    "Digital Adoption Platform",
    "Digital Workplaces Software",
    "Email Collaboration Tools",
    "Idea Management Software",
    "Innovation Software",
    "Intranet Software",
    "Meeting Management Software",
    "Meeting Room Booking System",
    "Presentation Software",
    "Remote Working Software",
    "Screen Sharing Software",
    "Team Communication Software",
    "Unified Communication System",
    "Video Calling Software",
    "Video Chat Software",
    "Video Conferencing Software",
    "Virtual Board Meeting Software",
    "Virtual Meeting Platform",
    "Visual Collaboration Software",
    "Webinar Software",
    "Work From Home Software",
    "3D Architecture Software",
    "Architectural CAD Software",
    "Architectural Rendering Software",
    "Architecture Design Software",
    "Autodesk Partner",
    "BIM Software",
    "Cabinet Design Software",
    "Civil Engineering Software",
    "Construction Accounting Software",
    "Construction Bidding Software",
    "Construction CRM Software",
    "Construction Design Software",
    "Construction Drawing Management Software",
    "Construction Estimating Software",
    "Construction Project Management Software",
    "Construction Scheduling Software",
    "Contractor Management Software",
    "Electrical Contractor Software",
    "Enterprise Architect Software",
    "Floor Plan Software",
    "Furniture Design Software",
    "HVAC Software",
    "HVAC Estimating Software",
    "Interior Design Tools",
    "Jobsite Management Software",
    "Kitchen Design Tools",
    "MEP Software",
    "MLS Software",
    "PIA Software",
    "Plumbing Software",
    "Plumbing Estimating Software",
    "Pool Design Software",
    "Punch List Software",
    "Real Estate Software",
    "Real Estate CMA Software",
    "Real Estate CRM Software",
    "Real Estate Investment Management Software",
    "Real Estate Marketing Software",
    "Real Estate Transaction Management Software",
    "Residential Construction Estimating Software",
    "Roofing Software",
    "Smart Building Software",
    "Takeoff Software",
    "Tender Management Software",
    "Blogging Platform",
    "Component Content Management System",
    "Content Analytics Software",
    "Content Audit Tools",
    "Content Creation Tools",
    "Content Curation Software",
    "Content Distribution Platform",
    "Content Experience Platform",
    "Content Writing Services",
    "Course Authoring Software",
    "Directory Software",
    "Enterprise Content Management Software",
    "Form Automation Software",
    "Form Management Software",
    "Grammar Checker Software",
    "Headless Content Management System",
    "Mobile Content Management System",
    "OCR Software",
    "Online Proofing Software",
    "Plagiarism Checker Software",
    "Proofreading Software",
    "Text Editor Software",
    "Translation Management Software",
    "User Generated Content Platform",
    "Word Processor Software",
    "Writing Tools",
    "A/B Testing Tools",
    "Customer Journey Mapping Software",
    "Heatmap Software",
    "Session Replay Software",
    "Churn Prediction Software",
    "Churn Prevention Software",
    "Client Management Software",
    "Client Onboarding Software",
    "Customer Advocacy Software",
    "Customer Data Platform",
    "Customer Database Software",
    "Customer Experience Management Software",
    "Customer Feedback Software",
    "Customer Loyalty Program Software",
    "Customer Reference Management Software",
    "Customer Success Software",
    "Experience Management Software",
    "Home Builder CRM Software",
    "Loyalty Management System",
    "Mac CRM Software",
    "Nonprofit CRM Software",
    "Online CRM Software",
    "Partner Relationship Management (PRM) Software",
    "Small Business Loyalty Programs Software",
    "Social CRM Software",
    "Zoho Partner",
    "Asset Tokenization Platform",
    "Blockchain Analysis Tools",
    "Blockchain Security Software",
    "Crypto Compliance Software",
    "Crypto Credit Cards Software",
    "Crypto Margin Trading Exchanges Platform",
    "Crypto Payment Solutions",
    "Crypto Portfolio Management Software",
    "Crypto Savings Platform",
    "Crypto Screeners Software",
    "Crypto Signals Software",
    "Crypto Staking Platform",
    "Crypto Tax Software",
    "Crypto Trading Bots Software",
    "Crypto Wallets Software",
    "Cryptocurrency Custody Software",
    "Cryptocurrency Exchanges Software",
    "DApp Browsers Platform",
    "Launchpads And IDO Platform",
    "NFT Platform",
    "NFT Creation Software",
    "P2P Crypto Exchanges Platform",
    "Smart Contract Platform",
    "Smart Contract Audit Services",
    "Yield Farming Platform",
    "Advocacy Software",
    "After Sales Service Management Software",
    "Chatbot Software",
    "Cobrowsing Software",
    "Community Management Software",
    "Complaint Management System",
    "Conversational Commerce Platform",
    "Conversational Support Software",
    "Customer Communications Management Software",
    "Customer Engagement Software",
    "Customer Retention Software",
    "Customer Satisfaction Software",
    "Customer Self Service Software",
    "Help Desk Software",
    "Live Chat Software",
    "Online Community Management Software",
    "OSS BSS System",
    "Queue Management Software",
    "Remote Support Software",
    "Self Hosted Help Desk Software",
    "Ticketing Management Software",
    "Virtual Agent Software",
    "Warranty Management Software",
    "Applied Behavior Analysis (ABA) Software",
    "Dashboard Software",
    "Mobile Analytics Software",
    "Personality Assessment Software",
    "Static Code Analysis Tools",
    "Text Mining Software",
    "User Research Software",
    "Big Data Tools",
    "Cloud Migration Software",
    "Cloud Storage Software",
    "CMDB Software",
    "Colocation Providers",
    "Consent Management Platform",
    "Cookie Tracking Software",
    "Data Center Management Software",
    "Data Discovery Tools",
    "Data Entry Software",
    "Data Extraction Software",
    "Data Governance Tools",
    "Data Integration Software",
    "Data Labeling Software",
    "Data Loss Prevention Software",
    "Data Masking Software",
    "Data Migration Software",
    "Data Mining Tools",
    "Data Pipeline Software",
    "Data Preparation Software",
    "Data Quality Tools",
    "Data Recovery Software",
    "Data Replication Software",
    "Data Security Software",
    "Data Visualization Tools",
    "Data Warehouse Tools",
    "Database Management System",
    "Database Monitoring Tools",
    "Device Control Software",
    "EDI Electronic Data Interchange Software",
    "Electronic Data Capture Software",
    "ETL Software",
    "Graph Database Platform",
    "Identity Resolution Software",
    "Identity Verification Software",
    "Master Data Management Software",
    "MIS Software",
    "Monitoring And Evaluation (M&E) Software",
    "Network Attached Storage Software",
    "NoSQL Database Platform",
    "Object Storage Software",
    "PDF Encryption Software",
    "PIM Software",
    "Product Data Management Software",
    "RDBMS Software",
    "Reference Management Software",
    "Spreadsheet Software",
    "Virtual Data Room Software",
    "Web Scraping Tools",
    "Advanced Distribution Management System",
    "Dealer Management System",
    "Direct Store Delivery Software",
    "Integrated Distribution System",
    "Last Mile Delivery Software",
    "Requirements Management Software",
    "Standard Operating Procedures Software",
    "Vendors Management Software",
    "Wholesale Distribution Software",
    "Document Collaboration Software",
    "Document Control Software",
    "Document Generation Software",
    "Document Tracking System",
    "Document Version Control Software",
    "Document Workflow Software",
    "File Management Software",
    "File Sharing Software",
    "File Storage Software",
    "File Sync Software",
    "Intelligent Document Processing Solutions",
    "Knowledge Base Software",
    "Legal Document Management Software",
    "Managed File Transfer Software",
    "Pdf Software",
    "Sharepoint Migration Tools",
    "Academic Advising Software",
    "Amazon Seller Tools",
    "Amazon Web Services Partner",
    "Android Kiosk Software",
    "Auction Software",
    "Automated Checkout Software",
    "B2B ECommerce Platform",
    "Catalog Management Software",
    "Dropshipping Software",
    "ECommerce Tools",
    "ECommerce Analytics Tools",
    "Ecommerce Integration Platform",
    "Ecommerce Marketing Platform",
    "Ecommerce Personalization Software",
    "Headless Ecommerce Platform",
    "Multi Channel ECommerce Software",
    "Omnichannel Communication Platform",
    "Online Marketplace Software",
    "Order Fulfillment Software",
    "Payment Gateway Services",
    "Price Monitoring Software",
    "Product Review Software",
    "Shopify Partner",
    "Shopping Cart Software",
    "Technical Skills Development Software",
    "Visual Product Customization Software",
    "Web To Print Software",
    "Accreditation Management Software",
    "Admissions Software",
    "Alumni Management Software",
    "Assessment & Examination Software",
    "Campus Management System",
    "Class Registration Software",
    "Classroom Management Software",
    "Classroom Scheduling Software",
    "Coaching Class Software",
    "College Management System",
    "Computer Skills Assessment Software",
    "Corporate LMS Software",
    "Course Management System",
    "Deep Learning Software",
    "Digital Education Platform",
    "ELearning Software",
    "Elearning Authoring Tools",
    "Ethics And Compliance Learning Software",
    "Exam Software",
    "Exam Builder Software",
    "Gradebook Software",
    "Higher Education Software",
    "Hostel Management Software",
    "Interactive Teaching Software",
    "K 12 Software",
    "Kids Learning Software",
    "Knowledge Management System",
    "Language Learning Software",
    "Learning Management System",
    "Library Automation Software",
    "Library Management Software",
    "Mentoring Software",
    "Micro Learning Software",
    "Mobile Learning Software",
    "Online Assessment Software",
    "Online Certification Platform",
    "Online Course Software",
    "Online Course Creation Software",
    "Online Proctoring Software",
    "Online Teaching Software",
    "Quiz Maker Software",
    "Sales Coaching Software",
    "Scholarship Management Software",
    "Skill Assessment Software",
    "Skills Management Software",
    "Student Engagement Software",
    "Student Information System",
    "Student Management System",
    "Test Maker Software",
    "Tutor Management Software",
    "University Management System",
    "Virtual Classroom Software",
    "Acumatica Partner",
    "APS Software",
    "Enterprise ERP Software",
    "Epicor Partner",
    "EProcurement Software",
    "Infor Partner",
    "Microsoft Partner",
    "Odoo Partner",
    "Operations Management Software",
    "Oracle Partner",
    "Procure To Pay Software",
    "Procurement Software",
    "Purchasing Software",
    "Resource Scheduling Software",
    "Sage Partner",
    "SAP Partner",
    "Small Business ERP Software",
    "Strategic Sourcing Software",
    "Audience Response Software",
    "Event Booking Software",
    "Event Checkin Software",
    "Event Marketing Software",
    "Event Registration Software",
    "Event Rental Software",
    "Event Tracking Software",
    "Festival Management Software",
    "Mobile Event Apps Software",
    "Online Event Ticketing Software",
    "Registration Software",
    "Sports League Software",
    "Tournament Software",
    "Venue Booking Software",
    "Venue Management Software",
    "Virtual Event Software",
    "Wait List Software",
    "Identity Management Software",
    "Visitor Management Software",
    "B2B Payment Platform",
    "BaaS Software",
    "Banking Software",
    "Bankruptcy Software",
    "Buy Now Pay Later Tools",
    "Chargeback Management Software",
    "Chit Fund Software",
    "Corporate And Retail Banking Software",
    "Credit Management Software",
    "Credit Repair Software",
    "Currency Exchange Software",
    "Debt Collection Software",
    "Donation Management Software",
    "Equity Management Software",
    "Expense Management Software",
    "Expense Tracking Software",
    "Financial Analytics Software",
    "Financial Close Software",
    "Financial Consolidation Software",
    "Financial CRM Software",
    "Financial Fraud Detection Software",
    "Financial Modeling Software",
    "Financial Reporting Software",
    "Financial Risk Management Software",
    "Financial Services Software",
    "Financial Wellness Platform",
    "Hedge Fund Software",
    "Investment Management Software",
    "Learning Experience Platform",
    "Loan Management Software",
    "Loan Origination Software",
    "Loan Servicing Software",
    "M&A Software",
    "Microfinance Banking Software",
    "Mobile Banking Software",
    "Mobile Credit Card Processing Software",
    "Money Lending Software",
    "Money Transfer Services",
    "Online Banking Software",
    "Payment Solutions",
    "Payment Management Software",
    "Payment Processing Software",
    "Payment Terminal Solutions",
    "Payslip Software",
    "PCI Compliance Software",
    "Personal Finance Software",
    "Portfolio Management Software",
    "Receipt Scanner Software",
    "Reconciliation Software",
    "Revenue Cycle Management Software",
    "Revenue Management Software",
    "Revenue Recognition Software",
    "Skip Tracing Software",
    "Spend Analysis Software",
    "Spend Management Software",
    "Telecom Expense Management Software",
    "Time And Expense Software",
    "Trade Show Software",
    "Treasury Software",
    "VAT Software",
    "Venture Capital Management Software",
    "Waiver Software",
    "Wireless Expense Management",
    "Bakery Software",
    "Brewery Software",
    "Canteen Management System",
    "Catering Management Software",
    "Food Costing Software",
    "Food Delivery Software",
    "Food Safety Software",
    "Food Service Distribution Software",
    "Food Traceability Software",
    "Online Food Ordering Software",
    "Church Management Software",
    "Church Presentation Software",
    "Crowdfunding Platform",
    "Donor Management Software",
    "Grant Management Software",
    "Volunteer Management Software",
    "Worship Software",
    "Geo Fencing Software",
    "Mapping Software",
    "Citizen Engagement Software",
    "Emergency Management System",
    "Environmental Software",
    "ESG Software",
    "Fire Department Software",
    "Forestry Tools",
    "Foster Care Software",
    "Municipal Software",
    "Nonprofit Software",
    "Permit Software",
    "Public Records Management Software",
    "Public Works Software",
    "RTO Agents Software",
    "Smart City Software",
    "Social Work Case Management Software",
    "Urban Planning Software",
    "Voting Software",
    "Water Management Software",
    "Wind Simulation Software",
    "3D Modeling Software",
    "3D Painting Software",
    "3D Printing Software",
    "3D Rendering Software",
    "Adobe Partner",
    "Animation Software",
    "Background Remover Software",
    "Business Card Software",
    "CAD Software",
    "Desktop Publishing Software",
    "Diagram Software",
    "Digital Art Software",
    "Drawing Tools",
    "Drawing CAD Software",
    "Electrical Design Software",
    "Fashion Designing Software",
    "Flipbook Software",
    "Flowchart Software",
    "Font Management Software",
    "Logo Design Software",
    "PCB Design Software",
    "Photo Editing Software",
    "Photo Organizing Software",
    "Photo Studio Software",
    "Photogrammetry Software",
    "Pixel Art Software",
    "Product Design Software",
    "Stock Photo Sites Platform",
    "Storyboard Software",
    "Vector Graphics Software",
    "Whiteboard Animation Software",
    "Blood Bank Management Software",
    "Healthcare Analytics Software",
    "Healthcare Compliance Software",
    "Healthcare CRM",
    "Population Health Management Solutions",
    "Ambulance Management Software",
    "Ayurvedic Software",
    "Child Care Software",
    "Chiropractic Software",
    "Clinic Management Software",
    "Clinical Decision Support System",
    "Clinical Trial Management System",
    "Dental Software",
    "Dental Charting Software",
    "Dental Imaging Software",
    "Dermatology Software",
    "Doctor Software",
    "Drug Discovery Software",
    "E Prescribing Software",
    "Electronic Health Record (EHR) Software",
    "Electronic Medical Records (EMR) Software",
    "EMS Emergency Medical Services Software",
    "Eye Protection Software",
    "Eye Tracking Software",
    "HIPAA Compliance Software",
    "Hospice Software",
    "Hospital Asset Management Software",
    "Hospital ERP Software",
    "Inpatient Management Software",
    "Long Term Care Software",
    "Massage Therapy Software",
    "Medical Imaging Software",
    "Medical Practice Management Software",
    "Medical Scheduling Software",
    "Medical Spa Software",
    "Medical Store Software",
    "Medical Transcription Software",
    "Mental Health Software",
    "MR Reporting Software",
    "Nurse Scheduling Software",
    "Nursing Home Software",
    "Nutrition Analysis Software",
    "Nutritionist Software",
    "Occupational Therapy Software",
    "OPD Management Software",
    "Optometry Software",
    "PACS Software",
    "Pathology Lab Software",
    "Patient Case Management Software",
    "Patient Engagement Software",
    "Patient Intake Software",
    "Patient Management Software",
    "Patient Portal Software",
    "Patient Registration Software",
    "Patient Scheduling Software",
    "Pattern Making Software",
    "Pediatric Software",
    "Pharma ERP Software",
    "Pharmaceutical Industry Software",
    "Pharmacy Software",
    "Physical Therapy Software",
    "Plastic Surgery Software",
    "Podiatry Software",
    "Practice Management Software",
    "Psychometric Software",
    "Radiology Software",
    "Remote Patient Monitoring Software",
    "Speech Therapy Software",
    "Telemedicine Software",
    "Vaccine Management System",
    "Veterinary Software",
    "Channel Management Software",
    "Concierge Software",
    "Hotel Booking Software",
    "Hotel Channel Management Software",
    "Hotel Front Desk Software",
    "Hotel Property Management System",
    "Reservation & Booking Software",
    "360 Degree Feedback Software",
    "Absence Management Software",
    "Applicant Tracking System",
    "Appointment Scheduling Software",
    "Artificial Intelligence Recruitment Software",
    "Attendance Management Software",
    "Attendance Tracking Software",
    "Background Check Software",
    "Background Verification Software",
    "Benefits Administration Software",
    "Biometric Attendance Software",
    "Candidate Evaluation Software",
    "Candidate Management Software",
    "Candidate Sourcing Software",
    "Career Management Software",
    "Compensation Management Software",
    "Competency Management System",
    "Contact Tracing System",
    "CSR Software",
    "Digital Signature Software",
    "Diversity Recruiting Software",
    "Electronic Signature Software",
    "Employee Advocacy Platform",
    "Employee Database Software",
    "Employee Engagement Software",
    "Employee Information Management System",
    "Employee Management System",
    "Employee Monitoring Software",
    "Employee Onboarding Software",
    "Employee Portal Software",
    "Employee Recognition Software",
    "Employee Record Software",
    "Employee Referral Software",
    "Employee Review Software",
    "Employee Scheduling Software",
    "Employee Self Service Software",
    "Employee Shift Scheduling Software",
    "Employee Survey Tools",
    "Employee Time Tracking Software",
    "Employee Tracking System",
    "Employee Training Software",
    "Employee Transport Management System",
    "Enterprise HR Software",
    "Executive Search Software",
    "Exit Interview Management Software",
    "Face Recognition Software",
    "Face Recognition Attendance System",
    "Gamification Software",
    "Goal Management Software",
    "Healthcare HR Software",
    "HR Analytics Tools",
    "HR Compliance Software",
    "HR Gamification Software",
    "HR Mobile Apps Software",
    "HRIS System",
    "HRMS Software",
    "Human Capital Management Software",
    "Human Services Software",
    "Interview Scheduling Software",
    "IWMS Software",
    "Job Board Software",
    "Job Costing Software",
    "Job Evaluation Software",
    "Job Portal Script Software",
    "Job Requisition Software",
    "Job Scheduling Software",
    "Job Search Platform",
    "Job Shop Software",
    "Leave Management System",
    "Manpower Planning Software",
    "OKR Software",
    "Online HR Software",
    "Online Payroll Software",
    "Payroll Software",
    "Payroll Outsourcing Services",
    "Performance Appraisal Software",
    "Performance Management Software",
    "Placement Management System",
    "Pre Employment Testing Software",
    "Productivity Management Software",
    "PTO Tracking Software",
    "Recruiting Software",
    "Recruiting Agency Software",
    "Recruitment Automation Software",
    "Recruitment CRM Software",
    "Recruitment Marketing Platform",
    "Reference Check Software",
    "Relocation Software",
    "Remote Onboarding Software",
    "Reporting Tools",
    "Resume Screening Software",
    "Salary Software",
    "Small Business HR Software",
    "Staffing Software",
    "Staffing Agency Software",
    "Stand Alone Payroll Software",
    "Succession Planning Software",
    "Talent Acquisition Software",
    "Talent Intelligence Platform",
    "Talent Management System",
    "Talent Marketplace Platform",
    "Time Clock Software",
    "Time Off Tracking Software",
    "Timesheet Software",
    "Timetable Management Software",
    "Video Interview Software",
    "Virtual Career Fair Platform",
    "Whistleblowing Software",
    "WorkFlow Management Software",
    "Workforce Analytics Software",
    "Workforce Management Software",
    "Workforce Optimization Software",
    "Workforce Planning Software",
    "Audit Management Software",
    "Corporate Tax Software",
    "Income Tax Filing Services",
    "Returns Management Software",
    "Sales Tax Software",
    "3D Scanning Software",
    "Any Industry Software",
    "Automobile Industry Software",
    "Electronics And Appliance Software",
    "Emissions Management Software",
    "Engineering Industry Software",
    "Fire Inspection Software",
    "Glass Industry Software",
    "Hardware And Paint Software",
    "Hardware Monitoring Software",
    "Industrial Automation Software",
    "Locksmith Software",
    "Oil And Gas Software",
    "Plastic Industry Software",
    "PLC Programming Software",
    "Plywood, Timber & Wood Industry Software",
    "Printing & Packaging Industry Software",
    "Public Safety Software",
    "SCADA Software",
    "Textile Industry Software",
    "Thermal Analysis Software",
    "Unknown Industry Software",
    "Claim Management Software",
    "Commercial Insurance Software",
    "Health Insurance Software",
    "Insurance Agency Software",
    "Insurance Analytics Software",
    "Insurance Claims Management Software",
    "Insurance Policy Software",
    "Insurance Rating Software",
    "Property And Casualty Insurance Software",
    "Consignment Software",
    "ECommerce Inventory Management Software",
    "Medical Inventory Software",
    "Order Entry Software",
    "Order Management Software",
    "Warehouse Management Software",
    "360 Degree Feedback Software",
    "Absence Management Software",
    "Applicant Tracking System",
    "Appointment Scheduling Software",
    "Artificial Intelligence Recruitment Software",
    "Attendance Management Software",
    "Attendance Tracking Software",
    "Background Check Software",
    "Background Verification Software",
    "Benefits Administration Software",
    "Biometric Attendance Software",
    "Candidate Evaluation Software",
    "Candidate Management Software",
    "Candidate Sourcing Software",
    "Career Management Software",
    "Compensation Management Software",
    "Competency Management System",
    "Contact Tracing System",
    "CSR Software",
    "Digital Signature Software",
    "Diversity Recruiting Software",
    "Electronic Signature Software",
    "Employee Advocacy Platform",
    "Employee Database Software",
    "Employee Engagement Software",
    "Employee Information Management System",
    "Employee Management System",
    "Employee Monitoring Software",
    "Employee Onboarding Software",
    "Employee Portal Software",
    "Employee Recognition Software",
    "Employee Record Software",
    "Employee Referral Software",
    "Employee Review Software",
    "Employee Scheduling Software",
    "Employee Self Service Software",
    "Employee Shift Scheduling Software",
    "Employee Survey Tools",
    "Employee Time Tracking Software",
    "Employee Tracking System",
    "Employee Training Software",
    "Employee Transport Management System",
    "Enterprise HR Software",
    "Executive Search Software",
    "Exit Interview Management Software",
    "Face Recognition Software",
    "Face Recognition Attendance System",
    "Gamification Software",
    "Goal Management Software",
    "Healthcare HR Software",
    "HR Analytics Tools",
    "HR Compliance Software",
    "HR Gamification Software",
    "HR Mobile Apps Software",
    "HRIS System",
    "HRMS Software",
    "Human Capital Management Software",
    "Human Services Software",
    "Interview Scheduling Software",
    "IWMS Software",
    "Job Board Software",
    "Job Costing Software",
    "Job Evaluation Software",
    "Job Portal Script Software",
    "Job Requisition Software",
    "Job Scheduling Software",
    "Job Search Platform",
    "Job Shop Software",
    "Leave Management System",
    "Manpower Planning Software",
    "OKR Software",
    "Online HR Software",
    "Online Payroll Software",
    "Payroll Software",
    "Payroll Outsourcing Services",
    "Performance Appraisal Software",
    "Performance Management Software",
    "Placement Management System",
    "Pre Employment Testing Software",
    "Productivity Management Software",
    "PTO Tracking Software",
    "Recruiting Software",
    "Recruiting Agency Software",
    "Recruitment Automation Software",
    "Recruitment CRM Software",
    "Recruitment Marketing Platform",
    "Reference Check Software",
    "Relocation Software",
    "Remote Onboarding Software",
    "Reporting Tools",
    "Resume Screening Software",
    "Salary Software",
    "Small Business HR Software",
    "Staffing Software",
    "Staffing Agency Software",
    "Stand Alone Payroll Software",
    "Succession Planning Software",
    "Talent Acquisition Software",
    "Talent Intelligence Platform",
    "Talent Management System",
    "Talent Marketplace Platform",
    "Time Clock Software",
    "Time Off Tracking Software",
    "Timesheet Software",
    "Timetable Management Software",
    "Video Interview Software",
    "Virtual Career Fair Platform",
    "Whistleblowing Software",
    "WorkFlow Management Software",
    "Workforce Analytics Software",
    "Workforce Management Software",
    "Workforce Optimization Software",
    "Workforce Planning Software",
    "Audit Management Software",
    "Corporate Tax Software",
    "Income Tax Filing Services",
    "Returns Management Software",
    "Sales Tax Software",
    "3D Scanning Software",
    "Any Industry Software",
    "Automobile Industry Software",
    "Electronics And Appliance Software",
    "Emissions Management Software",
    "Engineering Industry Software",
    "Fire Inspection Software",
    "Glass Industry Software",
    "Hardware And Paint Software",
    "Hardware Monitoring Software",
    "Industrial Automation Software",
    "Locksmith Software",
    "Oil And Gas Software",
    "Plastic Industry Software",
    "PLC Programming Software",
    "Plywood, Timber & Wood Industry Software",
    "Printing & Packaging Industry Software",
    "Public Safety Software",
    "SCADA Software",
    "Textile Industry Software",
    "Thermal Analysis Software",
    "Unknown Industry Software",
    "Claim Management Software",
    "Commercial Insurance Software",
    "Health Insurance Software",
    "Insurance Agency Software",
    "Insurance Analytics Software",
    "Insurance Claims Management Software",
    "Insurance Policy Software",
    "Insurance Rating Software",
    "Property And Casualty Insurance Software",
    "Consignment Software",
    "ECommerce Inventory Management Software",
    "Medical Inventory Software",
    "Order Entry Software",
    "Order Management Software",
    "Warehouse Management Software",
    "IT Service Management Software",
    "Azure Management Tools",
    "CFD Software",
    "Cisco Partner",
    "Click Fraud Software",
    "Cloud Computing Platform",
    "Cloud Workload Protection Platform",
    "Computer Monitoring Software",
    "Configuration Management Software",
    "Connected Worker Platform",
    "CPU Temperature Monitor Software",
    "Data Fabric Software",
    "Data Mapping Software",
    "Density Optimized Servers Software",
    "DEX Software",
    "Digital Experience Monitoring Software",
    "Digital Rights Management Software",
    "Digital Twin Software",
    "Driver Update Software",
    "Emergency Notification Software",
    "Endpoint Management Software",
    "Extranet Software",
    "Fax Server Software",
    "HPC Software",
    "Industrial Iot Software",
    "IT Software",
    "IT Alerting Software",
    "IT Automation Software",
    "IT Infrastructure Monitoring Tools",
    "IT Management Software",
    "IT Outsourcing Services",
    "Load Balancing Software",
    "Load Testing Tools",
    "Mac Protection Software",
    "Msp Software",
    "Network Automation Software",
    "Network Mapping Software",
    "Network Monitoring Software",
    "Network Troubleshooting Software",
    "Observability Tools",
    "Operating System",
    "Password Manager Software",
    "PC Cleaners Software",
    "Performance Testing Tools",
    "Problem Management Software",
    "Process Mining Tools",
    "Quantum Computing Software",
    "Real Time Operating System",
    "Remote Desktop Software",
    "Remote Monitoring And Management Software",
    "Request Management Software",
    "SaaS Management Software",
    "Screen Mirroring Software",
    "Server Backup Software",
    "Server Management Software",
    "Server Monitoring Tools",
    "Server Virtualization Software",
    "Serverless Platform",
    "Service Desk Management Software",
    "Siem Software",
    "Simulation Software",
    "Single Sign On Software",
    "System Monitoring Software",
    "Terminal Emulators Software",
    "User Activity Monitoring Software",
    "VDI Software",
    "Virtual IT Labs Software",
    "Virtual Private Cloud Software",
    "VPN Software",
    "Wan Optimization Software",
    "Web Accelerator Software",
    "Workload Automation Software",
    "Wysiwyg Software",
    "Laboratory Information Management System",
    "Lab Inventory Management Software",
    "Lab Management Software",
    "Life Sciences Software",
    "Medical Lab Software",
    "Legal Case Management Software",
    "Code Enforcement Software",
    "Conflict Check Software",
    "Court Management Software",
    "Docket System",
    "Electronic Discovery Software",
    "ENotary Software",
    "Enterprise Legal Management Software",
    "Immigration Software",
    "Incident Management Software",
    "Incident Response Software",
    "Investigation Management Software",
    "Jail Management Software",
    "Law Enforcement Software",
    "Law Firm And Advocates Software",
    "Law Practice Management Software",
    "Legal Calendaring Software",
    "Legal Hold Software",
    "Legal Research Software",
    "Litigation Management Software",
    "Maintenance Management Software",
    "Aviation Maintenance Software",
    "Carpet Cleaning Software",
    "Dry Cleaning Software",
    "Equipment Maintenance Software",
    "Janitor Software",
    "Laundry Management Software",
    "Plant Maintenance Software",
    "Pool Service Software",
    "Preventive Maintenance Software",
    "Manufacturing Software",
    "CAPA System",
    "Chemical Software",
    "Demand Planning Software",
    "Inspection Software",
    "Label Printing Software",
    "Manufacturing Execution System",
    "Manufacturing Intelligence Software",
    "Material Management Software",
    "MES System",
    "OEE Software",
    "Packaging Software",
    "Pharmaceutical Manufacturing Software",
    "PLM Software",
    "Product Configurator Software",
    "Product Management Tools",
    "Product Roadmap Software",
    "Production Management Software",
    "Production Scheduling Software",
    "Prototyping Software",
    "Quality Management Software",
    "Recycling Software",
    "Resource Management Software",
    "Robotic Process Automation Software",
    "Spc Software",
    "Tool Management Software",
    "Valve Manufacturing Software",
    "Workshop Management Software",
    "Marketing Automation Software",
    "Account Based Marketing Software",
    "Advertising Agency Software",
    "Affiliate Software",
    "AI Marketing Tools",
    "App Store Optimization (ASO) Tools",
    "Audience Intelligence Platform",
    "Blogger Outreach Software",
    "Brand Management Software",
    "Brand Monitoring Tools",
    "Brand Protection Software",
    "Bulk Email Software",
    "Bulk SMS Software",
    "Campaign Management Software",
    "Channel Marketing System",
    "Cold Email Software",
    "Content Marketing Software",
    "Contest Software",
    "Conversational Marketing Software",
    "Creative Management Platform",
    "Demo Automation Software",
    "Digital Marketing Tools",
    "Digital Signage Software",
    "Direct Mail Automation Software",
    "Display Advertising Software",
    "Drip Email Marketing Software",
    "Email Client Software",
    "Email Deliverability Tools",
    "Email Encryption Software",
    "Email Management Software",
    "Email Marketing Software",
    "Email Signature Software",
    "Email Testing Tools",
    "Email Tracking Software",
    "Email Verification Tools",
    "Enterprise Social Networking Software",
    "Field Force Automation Software",
    "Global Trade Management Software",
    "Influencer Marketing Software",
    "Link Management Tools",
    "Link Tracking Software",
    "Local Listing Management Software",
    "Local Marketing Software",
    "Localization Software",
    "Mailroom Management Software",
    "Market Research Software",
    "Marketing Analytics Tools",
    "Marketing Attribution Software",
    "Marketing Planning Software",
    "Marketplace Software",
    "Mass Texting Services",
    "MLM Software",
    "Mobile Advertising Software",
    "Mobile Marketing Platform",
    "MRM Software",
    "NPS Software",
    "Offer Management Software",
    "Personalization Software",
    "Political Campaign System",
    "PPC Software",
    "PR Software",
    "Publisher Ad Server Software",
    "Push Notification Services",
    "Rank Tracking Software",
    "Reddit Marketing Software",
    "Referral Software",
    "Reputation Management Software",
    "Retargeting Software",
    "Review Management Software",
    "Scheduling Software",
    "SEM Software",
    "SMS Blaster Software",
    "SMS Broadcast Software",
    "SMS Marketing Software",
    "Social Commerce Platform",
    "Social Media Scripts",
    "Social Media Advertising Software",
    "Social Media Analytics Tools",
    "Social Media Management Tools",
    "Social Media Monitoring Tools",
    "Social Network Software",
    "Statistical Analysis Software",
    "Tag Management Software",
    "Technology Review Platform",
    "Telegram Marketing Software",
    "Telemarketing Software",
    "Trade Promotion Management Software",
    "Transactional Email Services",
    "URL Shortener Tools",
    "Video Advertising Platform",
    "Video Marketing Software",
    "Voice Broadcasting Software",
    "Voicemail Software",
    "WhatsApp Business API Providers",
    "Whatsapp Marketing Software",
    "Wifi Marketing Software",
    "Membership Management Software",
    "Art Gallery Software",
    "Club Management Software",
    "Dance Studio Software",
    "Martial Arts Software",
    "Museum Software",
    "Pilates Studio Software",
    "Publishing And Subscriptions Software",
    "Subscription Management Software",
    "Tattoo Studio Software",
    "Yoga Studio Software",
    "Music Management Software",
    "Audio Editing Software",
    "Audio Recording Software",
    "DJ Software",
    "Music Notation Software",
    "Music Production Software",
    "Office Management Software",
    "Address Verification Software",
    "Age Verification Software",
    "Bookmark Manager Software",
    "Calendar Software",
    "Desk Booking Software",
    "Digital Voice Logging System",
    "File Converter Software",
    "Intercom Software",
    "Internal Communication Software",
    "Lost And Found Software",
    "Noise Cancellation Software",
    "Note Taking Software",
    "Org Chart Software",
    "Pdf Editors Software",
    "Polling Software",
    "Print Estimating Software",
    "Print Management Software",
    "Print On Demand Software",
    "Screen Recording Software",
    "Screenshot Tools",
    "Screenwriting Software",
    "Work Instructions Software",
    "Office Suites Software",
    "CAM Software",
    "Casino Management System",
    "Earthworks Software",
    "Enterprise Feedback Management Software",
    "Load Board Software",
    "Sales Prospecting Tools",
    "Personal Training Software",
    "Coding Challenge Platform",
    "Gym Management Software",
    "Gymnastics Software",
    "Resume Maker Software",
    "Self Assessment Software",
    "Audio Mixing Software",
    "Podcast Editing Software",
    "Podcast Hosting Software",
    "Podcast Recording Software",
    "Project Management Software",
    "Agile Project Management Tools",
    "Capital Project Management Software",
    "Earned Value Management",
    "Gantt Chart Software",
    "Issue Tracking Software",
    "Kanban Tools",
    "Predictive Analytics Software",
    "Project Cost Management Software",
    "Project Finance Management Software",
    "Project Planning Tools",
    "Project Portfolio Management Software",
    "Scrum Software",
    "Strategic Planning Software",
    "Survey Software",
    "Task Automation Software",
    "Task Management Software",
    "Team Management Software",
    "Time Management Software",
    "Time Tracking Software",
    "Vulnerability Management Tools",
    "Workflow Automation Software",
    "Property Management Software",
    "Apartment & Housing Society Software",
    "Assisted Living Software",
    "Building Maintenance Management Software",
    "Campground Management Software",
    "Commercial Real Estate Software",
    "Golfcourse Software",
    "HOA Software",
    "Home Builder Software",
    "Home Health Care Software",
    "Home Inspection Software",
    "Infrastructure Software",
    "Intellectual Property Management Software",
    "Land Management System",
    "Landscape Design Software",
    "Landscaping Software",
    "Lawn Care Software",
    "Lease Management Software",
    "Parking Management Software",
    "Parks And Recreation Software",
    "Physical Security Software",
    "Remodeling Estimating Software",
    "Rental Software",
    "Rental Property Management Software",
    "RERA Filing And Compliance Software",
    "Resort Management Software",
    "Shop Floor Management Software",
    "Space Management Software",
    "Student Housing Software",
    "Surveillance Software",
    "Timeshare System",
    "Yard Management System",
    "Restaurant Management Software",
    "Kitchen Display System",
    "Restaurant Data Analytics Software",
    "Restaurant POS Software",
    "Restaurant Reservations Software",
    "Restaurant Scheduling Software",
    "Tip Distribution Software",
    "Risk Management Software",
    "AML Software",
    "EHS Software",
    "GRC Software",
    "Integrated Risk Management (IRM) Software",
    "Operational Risk Management Software",
    "Policy Management Software",
    "Regulatory Change Management Software",
    "Third Party Risk Management Software",
     "Sales Management software",
    "Commission Software",
    "Contract Lifecycle Management Software",
    "CPQ Software",
    "Deal Management Software",
    "Electrical Estimating Software",
    "Field Sales Software",
    "Inside Sales Software",
    "Lead Capture Software",
    "Lead Generation Software",
    "Lead Management System",
    "Lead Nurturing Software",
    "Lead Scoring Software",
    "Opportunity Management Software",
    "Presales Software",
    "Pricing Optimization Software",
    "Proposal Management Software",
    "Quotation Management Software",
    "Quoting Software",
    "RFP Software",
    "Sales Acceleration Software",
    "Sales Analytics Software",
    "Sales And Operations Planning Software",
    "Sales Automation Tools",
    "Sales CRM Software",
    "Sales Enablement Software",
    "Sales Engagement Software",
    "Sales Forecasting Software",
    "Sales Gamification Software",
    "Sales Intelligence Software",
    "Sales Pipeline Management Software",
    "Sales Productivity Tools",
    "Sales Training Software",
    "Salesforce Partner",
    "Salesforce Integration Tools",
    "SFA Sales Force Automation Software",
    "Social Selling Tools",
    "Territory Management Software",
    "School Management software",
    "Driving School Software",
    "Music School Software",
    "School Accounting Software",
    "School Bus Routing Software",
    "School ERP Software",
    "School Time Table Software",
    "Swim School Software",
    "Security Management software",
    "Access Control System",
    "Ad Blocker Software",
    "Anti Phishing Software",
    "Anti Spam Software",
    "Anti Spyware Software",
    "Antivirus Software",
    "API Security Testing Tools",
    "Application Security Tools",
    "Authentication Software",
    "Cloud Security Software",
    "Credentialing Software",
    "CSPM Software",
    "Cyber Security Software",
    "DDoS Mitigation Tools",
    "Digital Forensics Software",
    "DMARC Software",
    "Dynamic Application Security Testing Software",
    "Email Security Software",
    "Encryption Software",
    "Endpoint Detection And Response (EDR) Software",
    "Endpoint Security Software",
    "Firewall Software",
    "Internet Security Software",
    "Iot Security Software",
    "IP Address Management Software",
    "Malware Analysis Tools",
    "Network Access Control Software",
    "Network Security Software",
    "Parental Control Software",
    "Patch Management Software",
    "Penetration Testing Tools",
    "Privileged Access Management Software",
    "Secure Web Gateways",
    "Platform Security Compliance Software",
    "Security System Installer",
    "System Service Mesh Tools",
    "Session Border Controller Software",
    "Software Composition Analysis Tools",
    "SSH Clients Software",
    "SSL Certificate Providers",
    "Static Application Security Testing Tools",
    "Threat Intelligence Platform",
    "Video Surveillance System",
    "Vulnerability Assessment Tools",
    "Website Accessibility Software",
    "Website Security Software",
    "Stock Market software",
    "Algo Trading Software",
    "Backtesting Software",
    "Copy Trading Platform",
    "CTRM Software",
    "Forex Trading Software",
    "Livestock Management Software",
    "Stock Analysis Software",
    "Stock Brokerage Software",
    "Technical Analysis Software",
    "Trading Software",
    "Supply Chain Management software",
    "Freight Forwarding Software",
    "Multicarrier Parcel Management Solutions",
    "Parcel Audit Software",
    "Rate Management Software",
    "Supplier Relationship Management Software",
    "Supply Chain Business Networks Software",
    "Supply Chain Planning System",
    "Supply Chain Visibility Software",
    "Terminal Operating System",
    "Tour and Travel Operator software",
    "Airline Reservation System",
    "Camp Management Software",
    "Travel Agency Software",
    "Travel Management Software",
    "Vacation Rental Software",
    "Training software",
    "Dynamic Learning & Training Software",
    "Online Training Software",
    "Safety Training Software",
    "Security Awareness Training Software",
    "Virtual Training Platform",
    "Transport Management software",
    "Auto Transport Software",
    "Autobody Software",
    "Car Rental Software",
    "Container Management Software",
    "Container Orchestration Software",
    "Courier Management Software",
    "Delivery Management Software",
    "Dock Scheduling Software",
    "Enterprise Vehicle Management Software",
    "Fleet Management Software",
    "Freight Software",
    "Fuel Management System",
    "Garage Door Software",
    "Garage Management Software",
    "GPS Tracking Software",
    "Limo Software",
    "Location Intelligence Software",
    "Logistics Software",
    "Marine Software",
    "Mileage Tracking Software",
    "Mobility Software",
    "Moving Software",
    "Public Transportation Software",
    "Rideshare Software",
    "Route Management Software",
    "Route Planning Software",
    "Self Storage Software",
    "Service Dispatch Software",
    "Shipment Tracking Software",
    "Shipping Software",
    "Taxi Dispatch Software",
    "Taxi Script Software",
    "Towing Software",
    "Transportation Dispatch Software",
    "Trucking Software",
    "Vehicle Tracking System",
    "Vessel Tracking System",
    "Weighbridge Software",
    "Utility software",
    "Cemetery Software",
    "Desktop Search Software",
    "Energy Management Software",
    "EV Charging Management Software",
    "Funeral Home Software",
    "Groundwater Modeling Software",
    "License Management Software",
    "Petrol Pump Software",
    "Solar Design Software",
    "Sustainability Software",
    "Video Management software",
    "Live Streaming Software",
    "Media Players Software",
    "OTT Platform",
    "Video Converter Software",
    "Video Downloader Software",
    "Video Editing Software",
    "Webcam Software",
    "Website Audit software",
    "Keyword Rank Checker Software",
    "Keyword Research Tools",
    "Optimisation Software",
    "SEO Software",
    "SEO Audit Tools",
    "Site Audit Software",
    "Website Builder software",
    "API Design Tools",
    "API Management Tools",
    "Bug Software",
    "Bug Fixing Software",
    "Bug Tracking Software",
    "Clone Scripts",
    "Cloud Hosting Services",
    "Cloud Management Software",
    "Continuous Integration Tools",
    "Custom Software Development Services",
    "Dark Web Monitoring Tools",
    "DevOps Tools",
    "DNS Server Software",
    "Exit Intent Popup Software",
    "Functional Testing Tools",
    "Game Development Software",
    "Hackathon Software",
    "IDE Software",
    "Java CMS Software",
    "Landing Page Software",
    "Manual Testing Tools",
    "No Code Development Platform",
    "PHP Scripts",
    "Portal Software",
    "Programming Software",
    "Test Management Tools",
    "UX Design Tools",
    "Web Accessibility Testing Software",
    "Web Analytics Tools",
    "Web Design Software",
    "Web Hosting Services",
    "Website Development Tools",
    "Website Monitoring Software",
    "Website Optimization Tools",
    "Zoo software",
    "Animal Shelter Software",
    "Horse Software",
    "Kennel Software",
    "Pet Grooming Software",
    "Pet Sitting Software"
]

class Spider2(scrapy.Spider):
    name = 'spider2'
    start_urls = ['https://www.softwaresuggest.com/']
    output_file = 'outputs.json'  # Define the output file
    bucket_name = 'dinostomach'
    folder_name = 'softwaresuggest'
    custom_settings = {
        'DOWNLOAD_DELAY' : 1,
        'ROBOTSTXT_OBEY': False
    }

    def parse(self, response):
        # Extracting links from the accordion_tab allsoftcategory divs
        for software_item in software_list:
            software_name = software_item.lower().replace(' ', '-')
            
            full_url = urljoin(response.url, software_name)
            print(full_url)
            yield scrapy.Request(full_url, callback=self.parse_software_page)

    def parse_software_page(self, response):
        # Extract software details
        software_sections = response.css('section.ga_track_soft_list.list_software_main.count_in')
        print(software_sections,"ss")
        for section in software_sections:
            software_info = {
    'title': section.css('a.d-flex.align-items-center.ga_track_soft_name::text').get(),
    'price': section.css('span.star_new_background::text').get(),
    'image_url': section.css('img.soft_logo.ls-is-cached.lazyloaded::attr(src)').get(),
    'profile_href': section.css('a.ga_track_soft_profile.view_profile_inline::attr(href)').get(),
    
 }
            print(software_info)
            
            if software_info['profile_href']:   # If profile exists on this page
            # Follow the profile link to extract the overview and overall review
                yield scrapy.Request(software_info['profile_href'], 
                                 callback=self.parse_software_profile, 
                                 meta={'software_info': software_info})

    def parse_software_profile(self, response):
        software_info = response.meta['software_info']
        # Extract the overview
        software_info['website']=response.css('a.ga_track_vwl_comp_d.specification_visit_website::attr(href)').get()
        software_info['image_url']=response.xpath('//img[not(@class)]')[2].attrib.get('src', None)
        software_info['description'] = response.css('p.read_more_text_overview::text').get()
        
        # Extract the overall review
        
        software_info['reviews'] = response.xpath("//h3[@class='main_review_heading_main'][position() <= 3]/text()").getall()

        print(software_info)

        # Check if the output file exists and write the scraped data
        file_exists = os.path.exists(self.output_file) and os.path.getsize(self.output_file) > 0
        with open(self.output_file, 'a') as json_file:
            if not file_exists:
                json_file.write('[')  # Add opening square bracket if the file is empty
            else:
                json_file.write(',')  # Add comma to separate JSON objects
            json.dump(software_info, json_file, indent=4)
        yield software_info


    def closed(self, reason):
        with open(self.output_file, 'a') as json_file:
            json_file.write(']')  # Add closing square bracket to indicate the end of JSON array

        
        s3 = boto3.client('s3',
                          aws_access_key_id=os.getenv('AWS_ACCESS_KEY_ID'),
                          aws_secret_access_key=os.getenv('AWS_SECRET_ACCESS_KEY'),
                          region_name=os.getenv('AWS_REGION'))

        # Load existing data from JSON file if it exists and is not empty
        if os.path.exists(self.output_file) and os.path.getsize(self.output_file) > 0:
            with open(self.output_file, 'r') as json_file:
                existing_data = json.load(json_file)

            total_items = len(existing_data)
            chunk_size = 1000
            num_chunks = ceil(total_items / chunk_size)

            for i in range(num_chunks):
                chunk = existing_data[i * chunk_size: (i + 1) * chunk_size]
                new_uuid = uuid.uuid4()
                chunk_file = f'products_chunk_{new_uuid}.json'
                
                # Save chunk to a separate JSON file
                with open(chunk_file, 'w') as chunk_json_file:
                    json.dump(chunk, chunk_json_file, indent=4)
                
                # Upload the chunk file to S3
                s3.upload_file(chunk_file, self.bucket_name, f'{self.folder_name}/{chunk_file}')
                self.logger.info(f'{chunk_file} uploaded to {self.bucket_name}/{self.folder_name}/{chunk_file}')

                # Remove the chunk file
                os.remove(chunk_file)