name: Trigger auto deployment for dinoserver

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/dinoserver-AutoDeployTrigger-70a6fc1f-dc18-491e-9af2-12f325ee66e1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DINOSERVER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DINOSERVER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DINOSERVER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: g2serverimage.azurecr.io
          registryUsername: ${{ secrets.DINOSERVER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DINOSERVER_REGISTRY_PASSWORD }}
          containerAppName: dinoserver
          resourceGroup: g2
          imageToBuild: g2serverimage.azurecr.io/dinoserver:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


